Update vvv-init.sh
Varying-Vagrant-Vagrants/custom-site-template pull request #29
Opened 2019-10-26 13:40 UTC by ironicmoka

Add wp theme install to the provisioner script

2019-10-26 13:42 UTC, ironicmoka commented
Just suggesting: I don't know if replicating those few lines is enough to make it work or more changes are needed.

2019-10-26 16:06 UTC, tomjn commented
This looks good, just needs testing

2019-10-27 13:23 UTC, Mte90 requested changes
It is missing an update to the readme

2019-10-28 09:54 UTC, Mte90 approved these changes

2019-10-28 09:54 UTC, merged